exam_management/urls.py
# exam_management/urls.py

from django.urls import path
from . import views
from django.views.generic.base import TemplateView
from .views import DeleteQuestionView, StudentExamStartView, StudentExamAttemptView, StudentExamScoreView, GlobalExamCompleteView, StudentExamAnalysisView, enter_manual_score, view_for_years, view_for_exams, ImageUploadView

app_name = 'exam_management'

urlpatterns = [
    path('exams/<category_type>/', views.ExamList.as_view(), name='exam_list_by_category'),
    path('exams/years/<category_type>/<entity_name>/', views.view_for_years, name='view_for_years'),
    path('exams/<category_type>/<entity_name>/<int:year>/', view_for_exams, name='view_for_exams'),
    path('category/<category_type>/', views.view_category_detail, name='view_category_detail'),
    path('exams/<int:pk>/', views.ExamDetail.as_view(), name='exam-detail'),
    path('exams/<int:exam_id>/questions/', views.QuestionList.as_view(), name='question-list'),
    path('questions/<int:pk>/', views.QuestionDetail.as_view(), name='question-detail'),
    path('exams/<int:exam_id>/manage', views.ManageExamView.as_view(), name='manage_exam'),
    path('ckeditor/upload/', ImageUploadView.as_view(), name='ckeditor_upload'),
    path('exams/<int:exam_id>/upload-csv', views.UploadQuestionsView.as_view(), name='upload_csv_questions'),
    path('questions/<int:pk>/edit', views.EditQuestionView.as_view(), name='edit_question'),
    path('exams/<int:pk>/edit', views.EditExamView.as_view(), name='edit_exam'),
    path('questions/<int:pk>/delete/', DeleteQuestionView.as_view(), name='question-delete'),
    path('exams/<int:exam_id>/publish', views.PublishExamView.as_view(), name='publish_exam'),
    path('start_exam/<int:exam_id>/', StudentExamStartView.as_view(), name='start_exam'),
    path('exam/no_questions/', views.no_questions_view, name='no_questions'),
    path('exam/invalid_question_index/', views.invalid_question_index_view, name='invalid_question_index'),
    path('global_exam_complete/', GlobalExamCompleteView.as_view(), name='global_exam_complete'),
    path('attempt_exam/<int:exam_id>/<int:attempt_id>/', StudentExamAttemptView.as_view(), name='attempt_exam_without_index'),
    path('attempt_exam/<int:exam_id>/<int:attempt_id>/<int:question_index>/', StudentExamAttemptView.as_view(), name='attempt_exam'),
    path('view_score/<int:exam_id>/<int:attempt_id>/', StudentExamScoreView.as_view(), name='view_score'),
    path('exam_analysis/<int:exam_id>/<int:attempt_id>/', StudentExamAnalysisView.as_view(), name='exam_analysis'),
    path('enter_manual_score/', enter_manual_score, name='enter_manual_score'),
    path('manual_score_success/', TemplateView.as_view(template_name='exam_management/manual_score_success.html'), name='manual_score_success'),
]

iexam/urls.py
# iexam/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include([
        path('api/user_management/', include(('user_management.api_urls', 'user_management_api'), namespace='user_management_api')),
        path('api/school_management/', include(('school_management.api_urls', 'school_management_api'), namespace='school_management_api')),
        path('api/class_management/', include(('class_management.api_urls', 'class_management_api'), namespace='class_management_api')),
        path('api/subject_management/', include(('subject_management.api_urls', 'subject_management_api'), namespace='subject_management_api')),
        path('api/exam_management/', include(('exam_management.api_urls', 'exam_management_api'), namespace='exam_management_api')),
        path('api/student_management/', include(('student_management.api_urls', 'student_management_api'), namespace='student_management_api')),
        path('api/performance_tracking/', include(('performance_tracking.api_urls', 'performance_tracking_api'), namespace='performance_tracking_api')),
        path('api/leaderboard/', include(('leaderboard.api_urls', 'leaderboard_api'), namespace='leaderboard_api')),
        path('api/media_management/', include(('media_management.api_urls', 'media_management_api'), namespace='media_management_api')),
        path('api/payments/', include('payments.api_urls')),
        path('api/subscription/', include('subscription.api_urls')),
    ])),
    # path('resource/', include('resource.urls', namespace='resource')),
    path('', include('user_management.urls', namespace='user_management_web')),
    path('class_management/', include('class_management.urls', namespace='class_management_web')),
    path('user_management/', include(('user_management.urls', 'user'), namespace='user_web')),
    path('school_management/', include(('school_management.urls', 'school'), namespace='school_web')),
    path('subject_management/', include(('subject_management.urls', 'subject'), namespace='subject_web')),
    path('exam_management/', include(('exam_management.urls', 'exam_management'), namespace='exam_management_web')),
    path('student_management/', include(('student_management.urls', 'student'), namespace='student_web')),
    path('performance_tracking/', include(('performance_tracking.urls', 'performance_tracking'), namespace='performance_tracking_web')),
    path('leaderboard/', include(('leaderboard.urls', 'leaderboard'), namespace='leaderboard_web')),
    path('media_management/', include(('media_management.urls', 'media_management'), namespace='media_management_web')),
    path('payments/', include('payments.urls')),
    path('subscription/', include('subscription.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam_management/models.py
# exam_management/models.py
from django.apps import apps
from django.utils import timezone
from django.db import models
from class_management.models import Subject, Teacher
from school_management.models import School
from subject_management.models import Topic, SubTopic
from random import shuffle
from django.core.exceptions import ValidationError
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import transaction
from ckeditor.fields import RichTextField
from markdownx.models import MarkdownxField 
import mammoth  # To convert .docx to HTML
from io import BytesIO
from tinymce.models import HTMLField

class ExamCategory(models.Model):
    CATEGORY_CHOICES = [
        ('CITAD', 'CENTER FOR INFORMATION TECHNOLOGY AND DEVELOPMENT'),
        ('POLY', 'Polytechnic'),
        ('COE', 'College of Education'),
        ('WAEC', 'WAEC'),
        ('NECO', 'NECO'),
        ('JAMB', 'JAMB'),
    ]
    category_type = models.CharField(max_length=100, choices=CATEGORY_CHOICES, default='CITAD')
    name = models.CharField(max_length=255)  # e.g., Name of the university, subject for WAEC/NECO, or year for JAMB
    year = models.IntegerField(null=True, blank=True)  # Year of the exam, applicable for all categories

    def __str__(self):
        return f"{self.get_category_type_display()} - {self.name} ({self.year})"
    
class Exam(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='exams')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='created_exams')
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='exams')
    name = models.CharField(max_length=255)
    category = models.ForeignKey(ExamCategory, on_delete=models.CASCADE, related_name='exams')
    number_of_questions = models.IntegerField()
    duration = models.DurationField()  # duration of the exam in minutes
    is_global = models.BooleanField(default=False, help_text="Check if this is a global exam")
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.subject.name} - {self.teacher.user.username}"

class Questions(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='questions')
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='questions')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='questions', null=True, blank=True)
    subtopic = models.ForeignKey(SubTopic, on_delete=models.CASCADE, null=True, blank=True, related_name='questions')
    instructions = RichTextField(null=True, blank=True)  
    question_text = HTMLField()
    explanation = HTMLField(null=True, blank=True) 
    question_image = models.ImageField(upload_to='questions/images/', null=True, blank=True)  # Image support
    question_pdf = models.FileField(upload_to='questions/pdfs/', null=True, blank=True)  # PDF support
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question_text[:50]

    # Method to create a new question with associated options
    @classmethod
    def create_from_parsed_data(cls, exam, school, question_data):
        # Create the question instance
        # Refactored media handling for more complex scenarios
        def append_media(media_list, base_text):
            for media in media_list:
                if media['type'] == 'image':
                    base_text += f"<img src=\"{media['src']}\" alt=\"image\">"
                elif media['type'] == 'mathml':
                    base_text += media['data']
                elif media['type'] == 'latex':
                    base_text += f'<span class="math-tex">{media["data"]}</span>'
                # Additional media types can be handled here
            return base_text

        question_text_with_media = append_media(question_data['media'], question_data['text'])
        question = cls.objects.create(
            exam=exam,
            school=school,
            topic=question_data.get('topic'),
            subtopic=question_data.get('subtopic'),
            question_text=question_text_with_media,
            instructions=question_data.get('instructions', ''),
            explanation=question_data.get('explanation', ''),
        )

        # Handle options
        for option_data in question_data['options']:
            option_text_with_media = append_media(option_data['media'], option_data['text'])
            Option.objects.create(
                question=question,
                option_text=option_text_with_media,
                is_correct=option_data['is_correct'],
            )

        return question

    def __str__(self):
        return self.question_text[:50]

class Option(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='options')
    option_text = HTMLField()
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.option_text[:50]
    
class ExamAttempt(models.Model):
    student_exam = models.ForeignKey('student_management.StudentExam', on_delete=models.CASCADE, related_name='attempts')
    questions = models.ManyToManyField('exam_management.Questions')
    current_question_index = models.PositiveIntegerField(default=0)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    time_remaining = models.PositiveIntegerField(null=True, blank=True)
    score = models.PositiveIntegerField(null=True, blank=True)
    completed = models.BooleanField(default=False)  # Field to mark if attempt is completed

    def calculate_score(self):
        total_questions = self.questions.count()
        correct_answers = 0
        
        for question in self.questions.all().prefetch_related('studentexamanswer_set'):
            student_answer_obj = question.studentexamanswer_set.filter(student_exam=self.student_exam).first()
            if student_answer_obj is None:
                continue

            if student_answer_obj.is_correct:
                correct_answers += 1

        # Calculate the percentage score and format it to two decimal places
        percentage_score = round((correct_answers / total_questions) * 100, 2) if total_questions > 0 else 0
            
        self.score = correct_answers
        self.save()

        return correct_answers, percentage_score

    def complete_attempt(self, request):
        StudentExamAnswer = apps.get_model('student_management', 'StudentExamAnswer')
        Option = apps.get_model('exam_management', 'Option')
            
        # Validation
        if self.current_question_index < self.questions.count() - 1:
            raise ValidationError("Attempt cannot be marked as complete as all questions have not been answered yet.")
            
        # Transaction ensures that these database operations are atomic
        with transaction.atomic():
            # Clear any existing answers for this exam attempt
            StudentExamAnswer.objects.filter(student_exam=self.student_exam).delete()
                
            # Populate StudentExamAnswer with the new answers stored in the session
            for question in self.questions.all():
                answer_id = request.session.get(f'answer_{self.student_exam.exam_id}_{question.id}', None)
                if answer_id:
                    is_correct = Option.objects.get(id=answer_id).is_correct
                    StudentExamAnswer.objects.create(student_exam=self.student_exam, question=question, student_answer_id=answer_id)

            # Mark the attempt as complete and calculate score
            self.end_time = timezone.now()
            self.calculate_score()

            # Clear session data related to this exam attempt
            for key in list(request.session.keys()):
                if key.startswith(f'answer_{self.student_exam.exam_id}_'):
                    del request.session[key]
                    
        self.save()
        
    def get_current_question(self):
        return self.questions.all()[self.current_question_index]

    def next_question(self):
        self.current_question_index += 1
        if self.current_question_index >= self.questions.count():
            self.completed = True  # Mark attempt as completed
            # Optionally, calculate and store score here
        self.save()

# Signal to initialize questions and start time for an ExamAttempt
@receiver(post_save, sender=ExamAttempt)
def initialize_questions(sender, instance, created, **kwargs):
    if created:  # Only if creating a new ExamAttempt
        # Initialize questions
        question_ids = list(instance.student_exam.exam.questions.values_list('id', flat=True))
        shuffle(question_ids)
        instance.questions.set(question_ids)
        
        # Set start time
        instance.start_time = timezone.now()
        instance.save()


class ManualScore(models.Model):
    student = models.ForeignKey('student_management.Student', on_delete=models.CASCADE, related_name='manual_scores')
    subject = models.ForeignKey('class_management.Subject', on_delete=models.CASCADE, related_name='manual_scores')
    teacher = models.ForeignKey('class_management.Teacher', on_delete=models.SET_NULL, null=True, blank=True, related_name='given_scores')
    ca1_score = models.PositiveIntegerField(null=True, blank=True)  # Continuous Assessment 1
    ca2_score = models.PositiveIntegerField(null=True, blank=True)  # Continuous Assessment 2
    exam_score = models.PositiveIntegerField(null=True, blank=True)  # Exam Score
    total_score = models.PositiveIntegerField(null=True, blank=True)  # Auto-calculated Total score

exam_management/templates/exam_management/delete_question.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container text-center">
    <h1 class="text-danger">Delete Question</h1>
    <p class="mb-4">Are you sure you want to delete this question: <span class="highlight-custom">"{{ object.question_text }}"</span>?</p>
    
    <form method="post" class="d-inline-block">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
    </form>
    
    <a href="{% url 'exam_management:question-detail' object.id %}" class="btn btn-primary ml-2">No, go back</a>
</div>
{% endblock %}

exam_management/templates/exam_management/exam_attempt.html
{% extends 'base_generic.html' %}
{% load my_filters %}

{% block content %}
<div class="container exam-container">
    <div id="timer-container">
        <div id="timer">Time Remaining: <span id="time"></span> minutes</div>
        <progress id="progress" value="{{ time_remaining }}" max="{{ exam_duration_in_seconds }}"></progress>
    </div>
    <div id="candidate">Candidate: {{ request.user.username }}</div>

    {% if current_question.instructions %}
        <div class="instructions-container">
            <strong>Instructions:</strong>
            <p>{{ current_question.instructions|safe }}</p>
        </div>
    {% endif %}
    
    <div class="question-container">
        <h6 class="highlight-custom">{{ current_question.question_text|safe }}</h6>
        {% if current_question.media %}
            {% for media_item in current_question.media %}
                {% if media_item.type == 'image' %}
                    <img src="{{ media_item.src }}" alt="Question Image">
                {% elif media_item.type == 'latex' %}
                    <span>\({{ media_item.data }}\)</span>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if current_question.question_image %}
            <img src="{{ current_question.question_image.url }}" alt="Question Image">
        {% endif %}
        {% if current_question.question_pdf %}
            <iframe src="{{ current_question.question_pdf.url }}" width="100%" height="600px">
                <p>Your browser doesn't support iframes.</p>
            </iframe>
        {% endif %}
    </div>
    
    <form id="exam-form" method="post" enctype="multipart/form-data" 
          action="{% url 'exam_management:attempt_exam' exam_id=exam_id attempt_id=attempt_id question_index=question_index %}" class="mt-4">
        {% csrf_token %}
        {% for option in form.selected_option.field.queryset %}
            <div class="form-check mb-2">
                <input type="radio" name="{{ form.selected_option.name }}" value="{{ option.id }}" 
                       id="option{{ option.id }}" class="form-check-input" 
                       {% if form.selected_option.value == option.id %}checked{% endif %}>
                <label for="option{{ option.id }}" class="form-check-label">
                    {{ forloop.counter|alpha_filter }}. {{ option.option_text|safe }}
                    {% if option.media %}
                        {% for media_item in option.media %}
                            {% if media_item.type == 'image' %}
                                <img src="{{ media_item.src }}" alt="Option Image">
                            {% elif media_item.type == 'latex' %}
                                <span>\({{ media_item.data }}\)</span>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </label>
            </div>
        {% endfor %}
    
        <div class="navigation-buttons">
            {% if not is_first_question %}
            <a href="{% url 'exam_management:attempt_exam' exam_id=exam_id attempt_id=attempt_id question_index=question_index|add:"-1" %}" class="btn btn-primary">
                Previous
            </a>
            {% endif %}
            {% if not is_last_question %}
            <button type="submit" class="btn btn-primary">Next</button>
            {% else %}
            <button type="submit" class="btn btn-success">Submit</button>
            {% endif %}
        </div>
    </form>
</div>
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML">
</script>
<script>
    // Function to start the timer
    function startTimer(duration, display) {
        var timer = duration;
        var countdown = setInterval(function() {
            var minutes = parseInt(timer / 60, 10);
            var seconds = parseInt(timer % 60, 10);
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.textContent = minutes + ":" + seconds;

            if (--timer < 0) {
                clearInterval(countdown);
                handleTimerExpiry(); // Handle the timer expiry
            } else {
                sessionStorage.setItem('timeRemaining', timer);
            }
        }, 1000);
    }

    // Function to handle timer expiry
function handleTimerExpiry() {
    // Make an AJAX call to auto-submit the exam
    var xhr = new XMLHttpRequest();
    xhr.open('POST', '/exam_management/attempt_exam/' + {{ exam_id }} + '/' + {{ attempt_id }} + '/0/', true); // Corrected URL
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-CSRFToken', getCookie('csrftoken')); // CSRF token handling

    xhr.onload = function() {
        if (xhr.status === 200) {
            // Redirect to the score view
            window.location.href = '/exam_management/view_score/' + {{ exam_id }} + '/' + {{ attempt_id }} + '/';
        } else {
            // Handle error
            console.error('Error in auto-submit:', xhr.responseText);
        }
    };

    xhr.send('auto_submit=true&exam_id=' + {{ exam_id }} + '&attempt_id=' + {{ attempt_id }});
}

    // Function to get CSRF token
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    // Add a function to re-typeset MathJax content when new question is loaded
    function typesetMathJax() {
        MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
    }

    // Call the typeset function after the DOM is fully loaded
    document.addEventListener('DOMContentLoaded', function() {
        typesetMathJax();
    });
    
    // Initialization on window load
    window.onload = function() {
        var initialTimeRemaining = {{ time_remaining }};
        var isNewAttempt = {{ is_new_attempt|lower }}; // Converts True/False to true/false

        if (isNewAttempt) {
            sessionStorage.removeItem('timeRemaining');
        }

        var storedTimeRemaining = sessionStorage.getItem('timeRemaining');

        if (!storedTimeRemaining) {
            sessionStorage.setItem('timeRemaining', initialTimeRemaining);
        }

        var timeRemaining = sessionStorage.getItem('timeRemaining');
        var display = document.querySelector('#time');
        startTimer(parseInt(timeRemaining, 10), display);
        // Call MathJax to typeset the page
        typesetMathJax();
    };
</script>
{% endblock %}

exam_management/templates/exam_management/exam_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container">
    <h1 class="highlight-custom">{{ object.name }}</h1>
    <p class="lead">Subject: {{ object.subject.name }}</p>
    <p>Number of Questions: {{ object.number_of_questions }}</p>
    <p>Duration: {{ object.duration }}</p>
    <p>Published: {{ object.is_published }}</p>

    <h2 class="services h2">Questions:</h2>
    {% for qwo in questions_with_options %}
      <div class="card mb-4">
          <div class="card-body">
              <p class="card-text"><strong>Question:</strong> {{ qwo.question.question_text }}</p>
              <p class="card-text"><strong>Instructions:</strong> {{ qwo.question.instructions }}</p>
              <ul>
              {% for option in qwo.options %}
                <li>{{ option.option_text }} {% if option.is_correct %}(Correct){% endif %}</li>
              {% endfor %}
              </ul>
          </div>
      </div>
    {% endfor %}
</div>
{% endblock %}

exam_management/templates/exam_management/exam_list.html
{% extends "base_generic.html" %}
{% load custom_filters %} <!-- Load the custom template filters, if you've created any -->

{% block content %}
<div class="container">
    <h1 class="highlight-custom">My Exams</h1>
    <table class="table mt-4">
        <thead>
            <tr>
                <th>Exam Name</th>
                <th>Category</th> <!-- New column for category -->
                <th>Subject</th>
                <th>Number of Questions</th>
                <th>Duration</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for exam in object_list %}
            <tr>
                <td>{{ exam.name }}</td>
                <td>{{ exam.category.get_category_type_display }} - {{ exam.category.name }} ({{ exam.category.year }})</td>
                <td>{{ exam.subject.name }}</td>
                <td>{{ exam.number_of_questions }}</td>
                <td>{{ exam.duration|format_duration }}</td> <!-- Using the custom filter for formatting duration -->
                <td>
                    {% if exam.is_published %}
                        Published
                    {% else %}
                        Unpublished
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'exam_management:exam-detail' exam.id %}" class="btn btn-info btn-sm">View</a>
                    <a href="{% url 'exam_management:edit_exam' exam.id %}" class="btn btn-warning btn-sm">Edit</a>
                    <a href="{% url 'exam_management:publish_exam' exam.id %}" class="btn btn-sm {% if exam.is_published %}btn-danger{% else %}btn-success{% endif %}">{{ exam.is_published|yesno:"Unpublish,Publish" }}</a>
                </td>
            </tr>
            {% empty %}
            <tr><td colspan="7">No exams available.</td></tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- Pagination Controls -->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

exam_management/templates/exam_management/exam_score.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container text-center">
    <h1 class="highlight-custom">Your Score: {{ score }}  {{ exam.number_of_questions }}</h1>
    <h2 class="mb-4">Percentage Score: {{ percentage_score }}%</h2>
    
    <div class="progress mb-4">
        <div class="progress-bar" role="progressbar" style="width: {{ percentage_score|floatformat:2 }}%;" aria-valuenow="{{ percentage_score|floatformat:2 }}" aria-valuemin="0" aria-valuemax="100">
            {{ percentage_score|floatformat:2 }}%
        </div>
    </div>
    
    {% if percentage_score >= 80 %}
        <h3 class="text-success">Excellent work!</h3>
    {% elif percentage_score >= 60 %}
        <h3 class="text-warning">Good job!</h3>
    {% else %}
        <h3 class="text-danger">Keep practicing!</h3>
    {% endif %}
    
    
  <!-- Add a button to view exam analysis -->
  <a href="{% url 'exam_management:exam_analysis' exam_id=exam_id attempt_id=attempt_id %}" class="btn btn-info">View Exam Analysis</a>
  
    <!-- You may add a button to review answers if needed -->
</div>
{% endblock %}

exam_management/templates/exam_management/exams_template.html
<!-- exams_template.html -->

{% extends "base_generic.html" %}
{% block content %}
<div class="container">
    <h2>Exams for {{ category_type }} - {{ year }}</h2>
    {% if exams %}
        <div class="card-deck">
            {% for exam in exams %}
                <div class="card my-3 border-primary">
                    <div class="card-header bg-primary text-white">
                        <h5 class="card-title">{{ exam.name }}</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-muted">{{ exam.subject.name }}</h6>
                        <p class="card-text">Duration: {{ exam.duration|stringformat:"i" }} minutes</p>
                        <p class="card-text">Total Questions: {{ exam.number_of_questions }}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'exam_management:start_exam' exam.id %}" class="btn btn-primary">Start Exam</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No exams available for this year.</p>
    {% endif %}
</div>
{% endblock %}

exam_management/templates/exam_management/manual_score_entry.html
<!-- exam_management/templates/exam_management/manual_score_entry.html -->

{% extends "base_generic.html" %}  <!-- Adjust based on your template structure -->

{% block content %}
  <h2>Enter Manual Score</h2>
  <form method="post" id="manualScoreForm">
      {% csrf_token %}
      <div>
          {{ form.student.label_tag }} {{ form.student }}
      </div>
      <div>
          {{ form.subject.label_tag }} {{ form.subject }}
      </div>
      <div>
          {{ form.teacher.label_tag }} {{ form.teacher }}
      </div>
      <div>
          {{ form.ca1_score.label_tag }} {{ form.ca1_score }} <small>(Optional)</small>
      </div>
      <div>
          {{ form.ca2_score.label_tag }} {{ form.ca2_score }} <small>(Optional)</small>
      </div>
      <div>
          {{ form.exam_score.label_tag }} {{ form.exam_score }} <small>(Optional)</small>
      </div>
      <div>
          {{ form.total_score.label_tag }} {{ form.total_score }} <small>(Auto-calculated if left blank)</small>
      </div>
      <div>
          {{ form.date_assigned.label_tag }} {{ form.date_assigned }}
      </div>
      <button type="submit">Submit</button>
  </form>
  <script>
    // Optional: JavaScript to auto-calculate total score
    document.getElementById('manualScoreForm').addEventListener('input', function() {
      // Get the score input values
      var ca1 = document.querySelector('#id_ca1_score').value || 0;
      var ca2 = document.querySelector('#id_ca2_score').value || 0;
      var exam = document.querySelector('#id_exam_score').value || 0;

      // Calculate the total
      var total = parseInt(ca1, 10) + parseInt(ca2, 10) + parseInt(exam, 10);
      
      // Update the total score field only if all the individual fields are filled
      if(ca1 && ca2 && exam) {
        document.querySelector('#id_total_score').value = total;
      }
    });
  </script>
{% endblock %}