iexam/urls.py
# iexam/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include([
        path('api/user_management/', include(('user_management.api_urls', 'user_management_api'), namespace='user_management_api')),
        path('api/school_management/', include(('school_management.api_urls', 'school_management_api'), namespace='school_management_api')),
        path('api/class_management/', include(('class_management.api_urls', 'class_management_api'), namespace='class_management_api')),
        path('api/subject_management/', include(('subject_management.api_urls', 'subject_management_api'), namespace='subject_management_api')),
        path('api/exam_management/', include(('exam_management.api_urls', 'exam_management_api'), namespace='exam_management_api')),
        path('api/student_management/', include(('student_management.api_urls', 'student_management_api'), namespace='student_management_api')),
        path('api/performance_tracking/', include(('performance_tracking.api_urls', 'performance_tracking_api'), namespace='performance_tracking_api')),
        path('api/leaderboard/', include(('leaderboard.api_urls', 'leaderboard_api'), namespace='leaderboard_api')),
        path('api/media_management/', include(('media_management.api_urls', 'media_management_api'), namespace='media_management_api')),
        path('api/payments/', include('payments.api_urls')),
        path('api/subscription/', include('subscription.api_urls')),
    ])),
    # path('resource/', include('resource.urls', namespace='resource')),
    path('', include('user_management.urls', namespace='user_management_web')),
    path('class_management/', include('class_management.urls', namespace='class_management_web')),
    path('user_management/', include(('user_management.urls', 'user'), namespace='user_web')),
    path('school_management/', include(('school_management.urls', 'school'), namespace='school_web')),
    path('subject_management/', include(('subject_management.urls', 'subject'), namespace='subject_web')),
    path('exam_management/', include(('exam_management.urls', 'exam_management'), namespace='exam_management_web')),
    path('student_management/', include(('student_management.urls', 'student'), namespace='student_web')),
    path('performance_tracking/', include(('performance_tracking.urls', 'performance_tracking'), namespace='performance_tracking_web')),
    path('leaderboard/', include(('leaderboard.urls', 'leaderboard'), namespace='leaderboard_web')),
    path('media_management/', include(('media_management.urls', 'media_management'), namespace='media_management_web')),
    path('payments/', include('payments.urls')),
    path('subscription/', include('subscription.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_management/urls.py
from django.urls import path
from . import views
from .views import (
    StudentPerformanceCreateView,
    StudentPerformanceUpdateView,
    StudentActivityCreateView,
    StudentActivityUpdateView,
    BehavioralAssessmentCreateView,
    BehavioralAssessmentUpdateView,
)


urlpatterns = [
    path('students/', views.StudentList.as_view(), name='student-list'),
    path('students/<int:pk>/', views.StudentDetail.as_view(), name='student-detail'),
    path('enrollments/', views.EnrollmentRequestList.as_view(), name='enrollment-request-list'),
    path('enrollments/<int:pk>/', views.EnrollmentRequestDetail.as_view(), name='enrollment-request-detail'),
    path('subject_selection/', views.SubjectSelectionView.as_view(), name='subject-selection'),  # New URL
    path('', views.index, name='index'),
    path('student/performance/create/', StudentPerformanceCreateView.as_view(), name='student_performance_create'),
    path('student/performance/<int:pk>/update/', StudentPerformanceUpdateView.as_view(), name='student_performance_update'),
    path('student/activity/create/', StudentActivityCreateView.as_view(), name='student_activity_create'),
    path('student/activity/<int:pk>/update/', StudentActivityUpdateView.as_view(), name='student_activity_update'),
    path('student/assessment/create/', BehavioralAssessmentCreateView.as_view(), name='behavioral_assessment_create'),
    path('student/assessment/<int:pk>/update/', BehavioralAssessmentUpdateView.as_view(), name='behavioral_assessment_update'),
]

payments/models.py
# payments/models.py
from django.db import models
from datetime import timedelta
from django.utils import timezone
from django.conf import settings
# Ensure to adjust this import to avoid circular dependencies
from subscription.models import Subscription  

PAYMENT_TYPES = [
    ('termly', 'Termly Payment'),
]

class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    subscription = models.ForeignKey(Subscription, on_delete=models.SET_NULL, null=True, blank=True, related_name='payments')  # Add this line
    reference = models.CharField(max_length=100)
    amount = models.IntegerField()
    status = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_type = models.CharField(choices=PAYMENT_TYPES, max_length=20, default='termly')
    term_end_date = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id and self.subscription:  # Check if this is a new instance and subscription is set
            # Adjust term_end_date based on the subscription's duration
            self.term_end_date = timezone.now() + timedelta(days=self.subscription.duration)
        super(Payment, self).save(*args, **kwargs)

student_management/forms.py
# student_management/forms.py
from django import forms
from class_management.models import Subject
from .models import (
    SubjectCombination,
    StudentExamAnswer,
    StudentPerformance,
    StudentActivity,
    BehavioralAssessment,
    Student,
)

class StudentPerformanceForm(forms.ModelForm):
    class Meta:
        model = StudentPerformance
        fields = ['student', 'subject', 'term', 'year', 'grade']

    def __init__(self, teacher=None, *args, **kwargs):
        super(StudentPerformanceForm, self).__init__(*args, **kwargs)
        if teacher:
            assigned_classes = teacher.classes.all()
            self.fields['student'].queryset = Student.objects.filter(enrolled_class__in=assigned_classes)

class StudentActivityForm(forms.ModelForm):
    class Meta:
        model = StudentActivity
        fields = ['student', 'activity_name', 'description', 'participation_level']

    def __init__(self, teacher=None, *args, **kwargs):
        super(StudentActivityForm, self).__init__(*args, **kwargs)
        if teacher:
            assigned_classes = teacher.classes.all()
            self.fields['student'].queryset = Student.objects.filter(enrolled_class__in=assigned_classes)

class BehavioralAssessmentForm(forms.ModelForm):
    class Meta:
        model = BehavioralAssessment
        fields = ['student', 'behavior', 'score', 'term', 'year']

    def __init__(self, teacher=None, *args, **kwargs):
        super(BehavioralAssessmentForm, self).__init__(*args, **kwargs)
        if teacher:
            assigned_classes = teacher.classes.all()
            self.fields['student'].queryset = Student.objects.filter(enrolled_class__in=assigned_classes)

class SubjectSelectionForm(forms.ModelForm):
    class Meta:
        model = SubjectCombination
        fields = ['subjects']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subjects'].queryset = Subject.objects.all()

            
class StudentExamAnswerForm(forms.ModelForm):
    class Meta:
        model = StudentExamAnswer
        fields = ['student_answer']


class AnswerForm(forms.Form):
    CHOICES = [(i, f'Option {i}') for i in range(1, 5)]
    selected_option = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

student_management/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views import View
from rest_framework import generics, exceptions
from django.views import generic
from .models import Student, EnrollmentRequest, StudentExam, StudentExamAnswer, StudentPerformance, StudentActivity, BehavioralAssessment
from .serializers import StudentSerializer, EnrollmentRequestSerializer
from .forms import SubjectSelectionForm, StudentPerformanceForm, StudentActivityForm, BehavioralAssessmentForm
from exam_management.models import Exam
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication
from django.views.generic.edit import FormView




class StudentList(generics.ListCreateAPIView):
    serializer_class = StudentSerializer

    def get_queryset(self):
        if hasattr(self.request.user, 'school_admin'):
            return Student.objects.filter(user__school=self.request.user.school_admin.school)
        elif hasattr(self.request.user, 'teacher'):
            return Student.objects.filter(enrolled_class__in=self.request.user.teacher.classes.all())
        elif hasattr(self.request.user, 'student'):
            return Student.objects.filter(id=self.request.user.student.id)
        else:
            return Student.objects.none()

class StudentDetail(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = StudentSerializer

    def get_queryset(self):
        if hasattr(self.request.user, 'school_admin'):
            return Student.objects.filter(user__school=self.request.user.school_admin.school)
        elif hasattr(self.request.user, 'teacher'):
            return Student.objects.filter(enrolled_class__in=self.request.user.teacher.classes.all())
        elif hasattr(self.request.user, 'student'):
            return Student.objects.filter(id=self.request.user.student.id)
        else:
            return Student.objects.none()

class EnrollmentRequestList(View):
    def get(self, request):
        if hasattr(request.user, 'school_admin'):
            pending_requests = EnrollmentRequest.objects.filter(
                school=request.user.school_admin.school, is_approved__isnull=True)
        else:
            pending_requests = EnrollmentRequest.objects.none()

        return render(request, 'student_management/enrollment_request_list.html', {
            'pending_requests': pending_requests
        })

    def post(self, request):
        selected_requests = request.POST.getlist('selected_requests')
        action = request.POST.get('action')

        if action == 'approve':
            EnrollmentRequest.objects.filter(id__in=selected_requests).update(is_approved=True)
        elif action == 'reject':
            EnrollmentRequest.objects.filter(id__in=selected_requests).update(is_approved=False)

        # Redirecting to the same page to reflect the changes
        return redirect('student:enrollment-request-list')

class EnrollmentRequestDetail(View):
    def get(self, request, pk):
        if hasattr(request.user, 'school_admin'):
            try:
                enrollment_request = EnrollmentRequest.objects.get(
                    pk=pk, school=request.user.school_admin.school)
            except EnrollmentRequest.DoesNotExist:
                # Handle error here, maybe redirect to an error page
                return redirect('error_page')
        else:
            # Handle error here, maybe redirect to an error page
            return redirect('error_page')

        return render(request, 'student_management/enrollment_request_detail.html', {
            'enrollment_request': enrollment_request
        })

    def post(self, request, pk):
        action = request.POST.get('action')
        if hasattr(request.user, 'school_admin'):
            try:
                enrollment_request = EnrollmentRequest.objects.get(
                    pk=pk, school=request.user.school_admin.school)

                if action == 'approve':
                    enrollment_request.is_approved = True

                    # If it's a teacher's request, update the teacher's status
                    if enrollment_request.teacher:
                        enrollment_request.teacher.is_approved = True
                        enrollment_request.teacher.save()

                    # If it's a student's request, update the student's status
                    if enrollment_request.student:
                        enrollment_request.student.is_approved = True
                        enrollment_request.student.save()

                elif action == 'reject':
                    enrollment_request.is_approved = False

                enrollment_request.save()
            except EnrollmentRequest.DoesNotExist:
                # Handle error here, maybe redirect to an error page
                return redirect('error_page')
        else:
            # Handle error here, maybe redirect to an error page
            return redirect('error_page')

        # Redirecting to the same page or another page as needed
        return redirect('user_management:school-admin-dashboard')

# new view to serve the template
def index(request):
    return render(request, 'student_management/index.html')
 
    
class SubjectSelectionView(View):
    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        # Fetch the logged in User instance
        user = request.user

        # Get the student instance related to the user
        student = Student.objects.get(user=user)

        # Initialize the form with the current subject combination of the student
        form = SubjectSelectionForm(instance=student.subject_combination)

        return render(request, 'student_management/subject_selection.html', {
            'form': form,
        })

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        # Fetch the logged in User instance
        user = request.user

        # Get the student instance related to the user
        student = Student.objects.get(user=user)

        # Update the student's subject combination with the submitted form data
        form = SubjectSelectionForm(request.POST, instance=student.subject_combination)
        if form.is_valid():
            form.save()

        return redirect('user_management:student_dashboard')


class StudentPerformanceCreateView(generic.CreateView):
    model = StudentPerformance
    form_class = StudentPerformanceForm
    template_name = 'student_management/student_performance_form.html'
    success_url = reverse_lazy('student_performance_list')  # Adjust the URL name as needed

class StudentPerformanceUpdateView(generic.UpdateView):
    model = StudentPerformance
    form_class = StudentPerformanceForm
    template_name = 'student_management/student_performance_form.html'
    success_url = reverse_lazy('student_performance_list')  # Adjust the URL name as needed

class StudentActivityCreateView(generic.CreateView):
    model = StudentActivity
    form_class = StudentActivityForm
    template_name = 'student_management/student_activity_form.html'
    success_url = reverse_lazy('student_activity_list')  # Adjust the URL name as needed

class StudentActivityUpdateView(generic.UpdateView):
    model = StudentActivity
    form_class = StudentActivityForm
    template_name = 'student_management/student_activity_form.html'
    success_url = reverse_lazy('student_activity_list')  # Adjust the URL name as needed

class BehavioralAssessmentCreateView(generic.CreateView):
    model = BehavioralAssessment
    form_class = BehavioralAssessmentForm
    template_name = 'student_management/behavioral_assessment_form.html'
    success_url = reverse_lazy('behavioral_assessment_list')  # Adjust the URL name as needed

class BehavioralAssessmentUpdateView(generic.UpdateView):
    model = BehavioralAssessment
    form_class = BehavioralAssessmentForm
    template_name = 'student_management/behavioral_assessment_form.html'
    success_url = reverse_lazy('behavioral_assessment_list')  # Adjust the URL name as needed

student_management/templates/student_management/behavioral_assessment_form.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>{% if object %}Edit{% else %}Add{% endif %} Behavioral Assessment</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

student_management/templates/student_management/bulk_enrollment_approval.html
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="action" value="A"> <!-- Hidden input for approval action -->
    <label>Select specific requests to approve:</label>
    {% for request in pending_requests %}
        <div>
            <input type="checkbox" name="selected_requests" value="{{ request.id }}">
            {{ request }} <!-- Display the request in the way you prefer -->
        </div>
    {% endfor %}
    <button type="submit">Submit</button>
</form>

student_management/templates/student_management/enrollment_request_detail.html
{% extends "base_generic.html" %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <h1>Enrollment Request Details</h1>
    
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">
                {% if enrollment_request.student %}
                    {{ enrollment_request.student.user.get_full_name|default:enrollment_request.student.user.username }}
                {% else %}
                    {{ enrollment_request.teacher.user.get_full_name|default:enrollment_request.teacher.user.username }}
                {% endif %}
            </h5>
            <p class="card-text">
                Course/Field: 
                {% if enrollment_request.student %}
                    {{ enrollment_request.student.class_or_department }}
                {% else %}
                    {{ enrollment_request.teacher.field_of_study }}
                {% endif %} <br>
                Status: {{ enrollment_request.get_status_display }} <br>
                School: {{ enrollment_request.school.name }} <br>
                <!-- Add more details as needed -->
            </p>
            <form method="post" action="{% url 'student:enrollment-request-detail' enrollment_request.id %}">
                {% csrf_token %}
                <button type="submit" name="action" value="approve" class="btn btn-success">Approve</button>
                <button type="submit" name="action" value="reject" class="btn btn-danger">Reject</button>
            </form>
        </div>
    </div>
{% endblock %}

student_management/templates/student_management/enrollment_request_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Enrollment Requests</h1>

    <form method="post" action="{% url 'student:enrollment-request-list' %}">
        {% csrf_token %}
        <div class="mb-3">
            <button type="submit" name="action" value="approve" class="btn btn-success">Bulk Approve Selected</button>
            <button type="submit" name="action" value="reject" class="btn btn-danger">Bulk Reject Selected</button>
        </div>
        {% for request in pending_requests %}
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">
                        <input type="checkbox" name="selected_requests" value="{{ request.id }}" class="me-2">
                        {% if request.student %}
                            <span title="{{ request.student.user.get_full_name }}">
                                <!-- Display initials and last name, or username if names are not provided -->
                                {{ request.student.user.first_name|first|default:"" }}{{ request.student.user.last_name|default:request.student.user.username }}
                            </span>
                            - Class/Department: {{ request.student.enrolled_class }}
                        {% else %}
                            <span title="{{ request.teacher.user.get_full_name }}">
                                {{ request.teacher.user.first_name|first|default:"" }}{{ request.teacher.user.last_name|default:request.teacher.user.username }}
                            </span>
                            - Field of Study: {{ request.teacher.field_of_study }}
                        {% endif %}
                    </h5>
                </div>
            </div>
        {% empty %}
            <p class="mt-3">No pending enrollment requests.</p>
        {% endfor %}
    </form>
{% endblock %}

student_management/templates/student_management/exam_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>Subject: {{ object.subject.name }}</p>
<p>Number of Questions: {{ object.number_of_questions }}</p>
<p>Duration: {{ object.duration }}</p>
<p>Published: {{ object.is_published }}</p>

<h2>Questions:</h2>
{% for qwo in questions_with_options %}
  <p>Question: {{ qwo.question.question_text }}</p>
  <p>Instructions: {{ qwo.question.instructions }}</p>
  <ul>
  {% for option in qwo.options %}
    <li>{{ option.option_text }} {% if option.is_correct %}(Correct){% endif %}</li>
  {% endfor %}
  </ul>
{% endfor %}
{% endblock %}

student_management/templates/student_management/exam_list.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Available Exams</h2>
  <ul>
    {% for exam in exams %}
      <li>
        <a href="{% url 'exam_detail' exam.id %}">{{ exam }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

student_management/templates/student_management/exam_result.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Exam Result</h2>
  <p>Your Score: {{ student_exam.score }}</p>
  <p>Total Questions: {{ student_exam.exam.questions.count }}</p>
  {% for answer in student_exam.answers.all %}
    <p>
      {{ answer.question.question_text }}
      <br>
      Your Answer: {{ answer.get_selected_option_display }}
      <br>
      Correct Answer: {{ answer.question.correct_option }}
    </p>
  {% endfor %}
{% endblock %}

student_management/templates/student_management/exam_selection.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Start Exams</button>
</form>

student_management/templates/student_management/index.html
<!-- student_management/templates/student_management/index.html -->

{% extends 'base.html' %}

{% block title %}
    Student Management - iExam
{% endblock title %}

{% block content %}
    <h1>Student Management Dashboard</h1>
    <!-- The rest of your homepage content goes here -->
{% endblock content %}

student_management/templates/student_management/question.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Questions for Exam: {{ exam.name }}</h1>

{% for question in object_list %}
  <p>Question: {{ question.question_text }}</p>
  <p>Topic: {{ question.topic.name }}</p>
  <p>Subtopic: {{ question.subtopic.name }}</p>
  <!-- You can add more details here -->
{% endfor %}
{% endblock %}

student_management/templates/student_management/select_subjects.html
<!-- templates/student_management/select_subjects.html -->
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Select Subjects</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Select</button>
  </form>
{% endblock %}

student_management/templates/student_management/student_performance_form.html
{% extends 'base_generic.html' %}  <!-- Adjust based on your base template -->

{% block content %}
  <h2>{% if object %}Edit{% else %}Add{% endif %} Student Performance</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

student_management/templates/student_management/subject_selection.html
{% extends 'base_generic.html' %}

{% block title %}
    Subject Selection - iExam
{% endblock title %}

{% block content %}
    <h1>Select Subjects</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ subject_selection_form.as_p }}
        <button type="submit">Update Subjects</button>
    </form>
{% endblock content %}

student_management/templates/student_management/take_exam.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>{{ exam.subject.name }}</h2>
  <h3>{{ exam.ExamDateAndTime }}</h3>
  {% for question in questions %}
    <div>
      <p>{{ question.question_text }}</p>
      <ul>
        <li>{{ question.option1 }}</li>
        <li>{{ question.option2 }}</li>
        <li>{{ question.option3 }}</li>
        <li>{{ question.option4 }}</li>
      </ul>
    </div>
  {% empty %}
    <p>No questions for this exam.</p>
  {% endfor %}
{% endblock %}